
from enum import Enum

class NumberConstructorConstants(Enum):
    CONTRACT_REVIEW_NUMBERING = 'CONTRACT_REVIEW_NUM_FORMAT'
    PURCHASE_ORDER_NUMBEING = 'PURCHASE_ORDER_NUM_FORMAT'
    PARTY_NUMBERING = 'PARTY_NUM_FORMAT'
    PRODUCT_NUMBERING = 'PRODUCT_NUM_FORMAT'
    CATEGORY_NUMBERING = 'CATEGORY_NUM_FORMAT'
    SUB_CATEGORY_NUMBERING = 'SUB_CATEGORY_NUM_FORMAT'
    ORDER_ACCEPTANCE_NUMBERING = "ORDER_ACCEPTANCE_NUM_FORMAT"
    WARE_HOUSE_NUMBERING = "WARE_HOUSE_NUMBERING"
    STORAGE_ZONE_NUMBERING = "STORAGE_ZONE_NUMBERING"
    PRODUCT_CATEGORY_NUMBERING = "PRODUCT_CATEGORY_NUMBERING"
    PRODUCT_SUB_CATEGORY_NUMBERING = "PRODUCT_SUB_CATEGORY_NUMBERING"
    PRODUCT_MASTER_NUMBERING = "PRODUCT_MASTER_NUMBERING"
    MATERIAL_RECEIPT_NUMBERING = "MATERIAL_RECEIPT_NUMBERING"
    TRC_NUMBERING = "TRC_NUMBERING"
    RACK_NUMBERING = "RACK_NUMBERING"
    PROJECT_CREATION_NUMBERING = "PROJECT_CREATION_NUMBERING"
    CURRENCY_TYPES = "CURRENCY_TYPES"
    INVOICE_NUMBERING = "INVOICE_NUMBERING"

